server:
  port: 8080
  shutdown: graceful

spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:h2:mem:numble;MODE=MySQL;
    username: sa
    password:
    hikari:
      connection-timeout: 1000
      maximum-pool-size: 10
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

---

server:
  port: 8080
  shutdown: graceful

spring:
  config:
    activate:
      on-profile: production
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/numble?useSSL=false&serverTimezone=Asia/Seoul
    hikari:
      connection-timeout: 1000
      maximum-pool-size: 10
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
